from Package_Animal.Creature import Creature

c1 = Creature(2,0)
print("Type: ",c1.type.nameType)
print("Level: ",c1.level)
print("Santé: ",c1.health)
print("Attaque: ",c1.attack)
print("Défence: ",c1.defense,"\n")

c2 = Creature(2,1)
print("Type: ",c2.type.nameType)
print("Level: ",c2.level)
print("Santé: ",c2.health)
print("Attaque: ",c2.attack)
print("Défence: ",c2.defense,"\n")

c3 = Creature(2,2)
print("Type: ",c3.type.nameType)
print("Level: ",c3.level)
print("Santé: ",c3.health)
print("Attaque: ",c3.attack)
print("Défence: ",c3.defense,"\n")

c4 = Creature(2,3)
print("Type: ",c4.type.nameType)
print("Level: ",c4.level)
print("Santé: ",c4.health)
print("Attaque: ",c4.attack)
print("Défence: ",c4.defense,"\n")

c5 = Creature(2,4)
print("Type: ",c5.type.nameType)
print("Level: ",c5.level)
print("Santé: ",c5.health)
print("Attaque: ",c5.attack)
print("Défence: ",c5.defense,"\n")

c6 = Creature(2,5)
print("Type: ",c6.type.nameType)
print("Level: ",c6.level)
print("Santé: ",c6.health)
print("Attaque: ",c6.attack)
print("Défence: ",c6.defense,"\n")

c7 = Creature(2,6)
print("Type: ",c7.type.nameType)
print("Level: ",c7.level)
print("Santé: ",c7.health)
print("Attaque: ",c7.attack)
print("Défence: ",c7.defense,"\n")

c8 = Creature(2,7)
print("Type: ",c8.type.nameType)
print("Level: ",c8.level)
print("Santé: ",c8.health)
print("Attaque: ",c8.attack)
print("Défence: ",c8.defense,"\n")

c9 = Creature(2,8)
print("Type: ",c9.type.nameType)
print("Level: ",c9.level)
print("Santé: ",c9.health)
print("Attaque: ",c9.attack)
print("Défence: ",c9.defense,"\n")

